Test/Test/Controllers/CommanController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmployeeApiConsumer.Controllers
{
    public class CommanController : Controller
    {
        public IActionResult Navigation()
        {
            ViewBag.UserName = HttpContext.Session.GetString("UserName");
            return View();
        }

        public IActionResult Selectors()
        {
            return View();
        }

        public IActionResult Getpartial(string selectView)
        {
            var res = "_Selector" + selectView;
            return PartialView(res);
        }

        public IActionResult Example()
        {
            return View();
        }

        public IActionResult Error(int code)
        {           
            ViewBag.RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
            ViewBag.ShowRequestId = !string.IsNullOrEmpty(ViewBag.RequestId);
            ViewBag.ErrorStatusCode = code;

            return View();
        }
    }
}

Test/Test/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using EmployeeApiConsumer.Services;
using Microsoft.AspNetCore.JsonPatch;
using EmployeeApiConsumer.Models;
using Microsoft.AspNetCore.Authorization;

namespace EmployeeManagement.Controllers
{

    public class EmployeeController : Controller
    {
        readonly EmployeeServices _employeeServices;
        readonly DepartmentServices _departmentServices;
        
        public EmployeeController(EmployeeServices employeeServices, DepartmentServices departmentServices)
        {
            _employeeServices = employeeServices;
            _departmentServices = departmentServices;
        }

        public ActionResult EmployeeDashboard()
        {
            return View();
            
        }

        public async Task<ActionResult> GetAllEmployees()
        {
            ViewBag.departments = await _departmentServices.GetDepartmentsAsync();
            var employees = await _employeeServices.GetEmployeesAsync();
            return PartialView("_EmployeeGrid", employees);

        }

        public async Task<ActionResult> Create()
        {  
            ViewBag.departments = await _departmentServices.GetDepartmentsAsync();          
            return PartialView("CreateNew");
        }

        public async Task<JsonResult> CreateEmployee(Employee employee)
        {
            var result =await _employeeServices.AddEmployeeAsync(employee);
            if (result)
            {
                return Json("Success");
            }
            return Json("Failed");
        }

        public async Task<ActionResult> Edit(int employeeId)
        {

            ViewBag.departments = await _departmentServices.GetDepartmentsAsync();
            var emp =await _employeeServices.GetEmployeeByIdAsync(employeeId);
            return PartialView("Edit", emp);
        }

        public async Task<ActionResult> EditEmp(Employee emp)
        {
            var respose = await _employeeServices.EditEmployeeAsync(emp);
            return Json("Record Updated Successfully");
        }

        public async Task<ActionResult> Delete(int id) 
        {
            var respose = await _employeeServices.DeletEmployeeAsync(id);
            return Json("Record Deleted Successfully");
        }

        public async Task<ActionResult> PatchEmployee([FromBody]JsonPatchDocument patchDocument,int id)
        {
            var response=await _employeeServices.PatchEmployee(patchDocument,id);
            return Json("Record Updated Successfully");
        }
    }
}

Test/Test/Views/Shared/CustomError.cshtml
@{
    ViewData["Title"] = "CustomError";
    var exception = ViewData["Exception"] as Exception;
}

<h1>An Error has Occurred</h1>

<p>@exception.Message</p>

Test/Test/Views/Shared/_EmployeeGrid.cshtml
@model IEnumerable<Employee>
@using Microsoft.AspNetCore.Mvc;
@using EmployeeApiConsumer.Models;
@{
    var depts = ViewBag.departments;

}

<h1 style="text-align:center">Admin Dashboard</h1>
<table style="background-color: aliceblue;">
    <thead>
        <tr>
            <th>Name</th>
            <th>Phone No</th>
            <th>Salary</th>
            <th>Designation</th>
            <th>Date of birth</th>
            <th>Email</th>
            <th>Department</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.PhoneNumber</td>
                <td>@item.Salary</td>
                <td>@item.Designation</td>
                <td>@item.DateOfBirth</td>
                <td>@item.EmailId</td>
                @foreach (var dpt in depts)
                {
                    if (item.DepartmentId == dpt.Id)
                    {
                        <td>@dpt.Name</td>
                    }
                }
                <td>

                    <input class="alert-info" type="submit" value="Edit" id="empid" onclick="EditEmployee(@item.Id)" />
                    <input class="alert-danger" type="submit" value="Delete" id="empid" onclick="confirmation(@item.Id,'@item.Name')" />

                    <div id="deleteModal" class="modal">
                        <div class="modal-content">
                            <span class="close">&times;</span>
                            <p>
                                Are you sure you want to delete <strong>
                                    <span id="empName"></span>?
                                </strong>
                            </p>
                            <button id="confirmDelete">Yes</button>
                            <button id="cancelDelete">No</button>
                        </div>
                    </div>

                </td>
            </tr>
        }
    </tbody>
</table>

Test/Test/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc;
@inject IHttpContextAccessor HttpContextAccessor
@{
    var jwtToken = HttpContextAccessor.HttpContext!.Session.GetString("token");
}

<!DOCTYPE html>
<html lang="en">

<head>

    <title>Training</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/css1/style.css" rel="stylesheet" />

    <script src="js1/jquery.min.js"></script>
    <script src="js1/popper.js"></script>
    <script src="js1/bootstrap.min.js"></script>
    <script src="js1/main.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</head>

<body>
    @if (jwtToken != null)
    {
        <div style="min-height:100vh;" class="wrapper d-flex align-items-stretch">
            <nav id="sidebar">
                <div class="custom-menu">
                    <button type="button" id="sidebarCollapse" class="btn btn-primary">
                        <i class="fa fa-bars"></i>
                        <span class="sr-only">Toggle Menu</span>
                    </button>
                </div>
                <div class="p-4">
                    <h1><a href="@Url.Action("Navigation", "Comman")" class="logo">Training <span>CAS Agency</span></a></h1>
                    <ul class="list-unstyled components mb-5">

                        <li>
                            <a href="@Url.Action("EmployeeDashboard", "Employee" )"><span class="fa fa-user mr-3"></span> Manage Employee</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Selectors", "Comman" )"><span class="fa fa-briefcase mr-3"></span> JQuery Selector</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Example", "Comman" )"><span class="fa fa-cogs mr-3"></span> Settings</a>
                        </li>
                        <li>
                            <a href="@Url.Action("UserLogout", "Account" )"><span class="fa fa-paper-plane mr-3"></span> LogOut</a>
                        </li>
                    </ul>



                    <div class="footer">
                        <p>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                            <br> All rights reserved <br> This template is made with <i class="icon-heart" aria-hidden="true"></i> by Prashant's Team.
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>

                </div>
            </nav>
            <div style="width:100%;">
                    @RenderBody()               
            </div>
        </div>
    }


</body>

</html>


<style>
    .center {
        margin-top: 5rem;
        display: flex;
        align-items: center;
        justify-content: center;
    }
</style>

Test/Test/Views/Shared/_SelectorClass.cshtml
<!-- for element -->
<div id="div-1">
	<div class="rightChild syntax">
		<span STYLE="font-weight:bold">Syntax : $(".class") </span><br>
		<span>
			Description: The .class selector selects all elements with the specific class. The class refers to the class attribute of an HTML element.

		</span>

	</div>
	<hr />

	<div class="rightChild code">
		<span STYLE="font-weight:bold">Get it visualized by selecting a class... </span><br>
		<!-- <p> <span> $(' <input type="text" id="find" name="find" placeholder="element name.."> ')</span> </p> -->

		<label for="element">Choose an element : </label>
		<span>
			$('.
			<select name="element" id="find">
				<option value="">Select</option>
				<option value="Heading">heading</option>
				<option value="SubHeading">SubHeading</option>
				<option value="classA">Class-A </option>
				<option value="classC">Class-C</option>
				<option value="formDeatils">formDeatils</option>
				
			</select> ')
		</span>


		<input style="margin-left: 1rem;" type="button" id="class-Button" value="Try out !!" />
		<input style="margin-left: 1rem;" type="button" id="class-reset" value="Reset.." />
		<div id="display"></div>
		<div id="myDiv" style="display: none;">hii</div>
		<div id="code"></div>
		<div id="code2"></div>
	</div><hr />
	<div class="rightChild html-block">

		<h1 class="Heading" style="text-align:center">I'm < h1> with class "heading"</h1>
		<h2 class="SubHeading" style="text-align:center">I'm Sub heading with class "SubHeading"</h2>
		<div class="intro">
			<p>
				I'm < p> tag !! The < p> tag defines a paragraph.
				Browsers automatically add a single blank line before and after each < p> element.
			</p>


		</div>
		<div style="display:inline-flex; text-align:center" id="boxes"; class="BoxContainer">

			<div class="classA" id="leftbox">
				<h2>Class A</h2>
				<span class="spanText">
					The < div> tag defines a division or a section in an HTML document.Browsers always place a line break before and after element.
				</span>
			</div>

			<div class="classB" id="middlebox">
				<h2>Class B</h2>
				<span class="spanText">
					The < div> tag is used as a container for HTML elements - which is then styled with
					CSS or manipulated with JavaScript.
				</span>
			</div>

			<div class="classC" id="rightbox">
				<h2>Class C:</h2>
				<span class="spanText">
					The < div> tag is easily styled by using the class or id attribute. Any sort of
					content can be put inside the < div> tag!
				</span>
			</div>
		</div><br />

		<hr />
		<br />
		
		<div style="background-color:aliceblue;" >
			

		<form class="formDeatils">
				<div style="padding:4rem; text-align:center;">
			<br />
			<label for="name">Name:</label>
			<input type="text" id="name" name="name">
			<label for="email">Email:</label>
			<input type="email" id="email" name="email"><br><br />

			<label for="option1">Option 1:</label>
			<input type="checkbox" id="option1" name="option1" value="option1">

			<label for="option2">Option 2:</label>
			<input type="checkbox" id="option2" name="option2" value="option2"><br><br />

			<label for="gender">Gender:</label><br>
			<input type="radio" id="male" name="gender" value="male">
			<label for="male">Male</label>

			<input type="radio" id="female" name="gender" value="female">
			<label for="female">Female</label><br /><br />

			<input type="button" value="submit" />
			<input type="reset" value="reset" />
			<input type="hidden" value="cancel" /><br />
			<p></p>
				</div>
		</form>
			
		</div>
		<br />
		<br />

	</div>


</div>


<script>

	$(function () {
		$('#class-Button').click(function () {

			var elementName = $('#find').val();
			$('.rightChild.html-block').find('*').css({
				'background-color': '',
				'border': '',
				'color':'black'
			});

			$('.rightChild.html-block').find("." + elementName).css({
				'background-color': '#3445b4'
			});

			$('.rightChild.html-block').find("." + elementName).css({
				'color': 'white'
			});
			$('.rightChild.html-block').find("." + elementName).find('*').css({
				'color': 'white'
			});


			var container = $('#flex-child-right');
			var scrollTo = $("." + elementName)[0];

			$(container).animate({
				scrollTop: $("." + elementName).offset().top
			}, 1000);
		});

		// reset
		$('#class-reset').click(function () {
			$('#find').val = '';
			$('.rightChild.html-block').find('*').css({
				'background-color': '',
				'border': ''
			});

			$('.rightChild.html-block').find('*').css({
				'color': 'black'
			});
		});


	});

</script>

Test/Test/Views/Shared/_SelectorEven.cshtml
<!-- for element -->
<div id="div-1">
	<div class="rightChild syntax">
		<span STYLE="font-weight:bold">Syntax : $(":even") </span><br><br>
		<span>
			Description: The :even selector selects each element with an even index number (like: 0, 2, 4, etc.). The index numbers start at 0.
		</span>
	</div>

	<div class="rightChild code">
		<span STYLE="font-weight:bold">Get it visualized by selecting an element... </span><br><br>
		<!-- <p> <span> $(' <input type="text" id="find" name="find" placeholder="element name.."> ')</span> </p> -->

		<label for="element">Choose an element : </label>
		<span>
			$('
			<select name="element" id="find">
				<option value="">Select</option>
				<option value="p">p:even</option>
				<option value="div">div:even</option>
				<option value="tr">tr:even</option>
				
			</select> ')
		</span>


		<input style="margin-left: 1rem;" type="button" id="class-Button" value="Try out !!" />
		<input style="margin-left: 1rem;" type="button" id="class-reset" value="Reset" />
		<div id="display"></div>
		<div id="myDiv" style="display: none;">hii</div>
		<div id="code"></div>
		<div id="code2"></div>
	</div>
	<div class="rightChild html-block">

		<h1 class="Heading" style="text-align:center">Hello! I'm < h1> Headling element</h1>
		<h2 class="headingh2" style="text-align:center">This is heading with < h2> element</h2>
		<div class="intro">
			<p>I'm < p> tag !! The < p> tag defines a paragraph.
					Browsers automatically add a single blank line before and after each < p> element.</p>
			
				  <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quam delectus iusto voluptas deleniti? Error, at? 
					  Beatae perferendis optio quisquam? Dolores quidem pariatur quisquam, aliquid ipsum commodi laborum hic recusandae, 
					  fugiat mollitia sapiente? 
					  </p>
					  <p>Quae quaerat praesentium dolorem optio quisquam rem culpa, quidem voluptatem itaque tempora 
					  doloremque quam quos nisi consequuntur atque.
				  </p>

			
		</div>
		<h3 style="text-align:center">Play with Div's</h3>
		<div style="display:inline-flex; " id="boxes">

			<div class="divconatiner" id="leftbox">
				<h2>Div A:</h2>
				<span class="spanText">
					The < div> tag defines a division or a section in an HTML document.Browsers always place a line break before and after element.
				</span>
			</div>

			<div id="middlebox">
				<h2>Div B:</h2>
				<span class="spanText">
					The < div> tag is used as a container for HTML elements - which is then styled with
						CSS or manipulated with JavaScript.
				</span>
			</div>

			<div id="rightbox">
				<h2>Div C:</h2>
				<span class="spanText">
					The < div> tag is easily styled by using the class or id attribute. Any sort of
						content can be put inside the < div> tag!
				</span>
			</div>
		</div>

		<table>
			<tr>
				<th>Company</th>
				<th>Contact</th>
				<th>Country</th>
			</tr>
			<tr>
				<td>Alfreds Futterkiste</td>
				<td>Maria Anders</td>
				<td>Germany</td>
			</tr>
			<tr>
				<td>Centro comercial Moctezuma</td>
				<td>Francisco Chang</td>
				<td>Mexico</td>
			</tr>
			<tr>
				<td>Ernst Handel</td>
				<td>Roland Mendel</td>
				<td>Austria</td>
			</tr>

		</table>
		


		<form id="formid" class="form">
			<br />
			<label for="name">Name:</label>
			<input type="text" id="name" name="name">
			<label for="email">Email:</label>
			<input type="email" id="email" name="email"><br><br />

			<label for="option1">Option 1:</label>
			<input type="checkbox" id="option1" name="option1" value="option1">

			<label for="option2">Option 2:</label>
			<input type="checkbox" id="option2" name="option2" value="option2"><br><br />

			<label for="gender">Gender:</label><br>
			<input type="radio" id="male" name="gender" value="male">
			<label for="male">Male</label>

			<input type="radio" id="female" name="gender" value="female">
			<label for="female">Female</label><br /><br />

			<input type="button" value="submit"/>
			<input type="reset" value="reset"/>
			<input type="hidden" value="cancel"/><br />
			<p></p>
		</form>

	</div>


</div>


<script>

	$(function () {
		$('#class-Button').click(function () {

			var elementName = $('#find').val();
			$('.rightChild.html-block').find('*').css({
				'background-color': '',
				'border': ''
			});

			$('.rightChild.html-block').find(elementName + ":even").css({
				'background-color': 'rgb(231, 166, 166)',
				'border': '1px solid black'
			});
		});

		// reset
		$('#class-reset').click(function () {
			$('#find').val = '';
			$('.rightChild.html-block').find('*').css({
				'background-color': '',
				'border': ''
			});
		});
	});

</script>

Test/Test/Views/Shared/_SelectorFirst.cshtml
<!-- for element -->
<div id="div-1">
	<div class="rightChild syntax">
		<span STYLE="font-weight:bold">Syntax : $(":first") </span><br><br>
		<span>
			Description: The :first selector selects the first element.This is mostly used together with another selector to select the first element in a group.
			
		</span>
	</div>

	<div class="rightChild code">
		<span STYLE="font-weight:bold">Get it visualized by selecting an element... </span><br><br>
		<!-- <p> <span> $(' <input type="text" id="find" name="find" placeholder="element name.."> ')</span> </p> -->

		<label for="element">Choose an element : </label>
		<span>
			$('
			<select name="element" id="find">
				<option value="">Select</option>
				<option value="p">p:first</option>
				<option value="span">span:first</option>
				<option value="h2">h2:first</option>
				
			</select> ')
		</span>


		<input style="margin-left: 1rem;" type="button" id="class-Button" value="Try out !!" />
		<input style="margin-left: 1rem;" type="button" id="class-reset" value="Reset" />
		<div id="display"></div>
		<div id="myDiv" style="display: none;">hii</div>
		<div id="code"></div>
		<div id="code2"></div>
	</div>
	<div class="rightChild html-block">

		<h1 class="Heading" style="text-align:center">Hello! I'm < h1> Headling element</h1>
		<h2 class="headingh2" style="text-align:center">This is heading with < h2> element</h2>
		<div class="intro">
			<p>I'm < p> tag !! The < p> tag defines a paragraph.
					Browsers automatically add a single blank line before and after each < p> element.</p>
			
				  <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quam delectus iusto voluptas deleniti? Error, at? 
					  Beatae perferendis optio quisquam? Dolores quidem pariatur quisquam, aliquid ipsum commodi laborum hic recusandae, 
					  fugiat mollitia sapiente? Quae quaerat praesentium dolorem optio quisquam rem culpa, quidem voluptatem itaque tempora 
					  doloremque quam quos nisi consequuntur atque.
				  </p>

			
		</div>
		<h3 style="text-align:center">Play with Div's</h3>
		<div style="display:inline-flex; " id="boxes">

			<div class="divconatiner" id="leftbox">
				<h2>Div A:</h2>
				<span class="spanText">
					The < div> tag defines a division or a section in an HTML document.Browsers always place a line break before and after element.
				</span>
			</div>

			<div id="middlebox">
				<h2>Div B:</h2>
				<span class="spanText">
					The < div> tag is used as a container for HTML elements - which is then styled with
						CSS or manipulated with JavaScript.
				</span>
			</div>

			<div id="rightbox">
				<h2>Div C:</h2>
				<span class="spanText">
					The < div> tag is easily styled by using the class or id attribute. Any sort of
						content can be put inside the < div> tag!
				</span>
			</div>
		</div>

		<table>
			<tr>
				<th>Company</th>
				<th>Contact</th>
				<th>Country</th>
			</tr>
			<tr>
				<td>Alfreds Futterkiste</td>
				<td>Maria Anders</td>
				<td>Germany</td>
			</tr>
			<tr>
				<td>Centro comercial Moctezuma</td>
				<td>Francisco Chang</td>
				<td>Mexico</td>
			</tr>
			<tr>
				<td>Ernst Handel</td>
				<td>Roland Mendel</td>
				<td>Austria</td>
			</tr>

		</table>
		


		<form id="formid" class="form">
			<br />
			<label for="name">Name:</label>
			<input type="text" id="name" name="name">
			<label for="email">Email:</label>
			<input type="email" id="email" name="email"><br><br />

			<label for="option1">Option 1:</label>
			<input type="checkbox" id="option1" name="option1" value="option1">

			<label for="option2">Option 2:</label>
			<input type="checkbox" id="option2" name="option2" value="option2"><br><br />

			<label for="gender">Gender:</label><br>
			<input type="radio" id="male" name="gender" value="male">
			<label for="male">Male</label>

			<input type="radio" id="female" name="gender" value="female">
			<label for="female">Female</label><br /><br />

			<input type="button" value="submit"/>
			<input type="reset" value="reset"/>
			<input type="hidden" value="cancel"/><br />
			<p></p>
		</form>

	</div>


</div>


<script>

	$(function () {
		$('#class-Button').click(function () {

			var elementName = $('#find').val();
			$('.rightChild.html-block').find('*').css({
				'background-color': '',
				'border': ''
			});

			$('.rightChild.html-block').find(elementName + ":first").css({
				'background-color': 'rgb(231, 166, 166)',
				'border': '1px solid black'
			});
		});

		// reset
		$('#class-reset').click(function () {
			$('#find').val = '';
			$('.rightChild.html-block').find('*').css({
				'background-color': '',
				'border': ''
			});
		});
	});

</script>

Test/Test/Views/Shared/_SelectorId.cshtml
<!-- for element -->
<div id="div-1">
    <div class="rightChild syntax">
        <span STYLE="font-weight:bold">Syntax : $(".class") </span><br>
        <span>
            Description: The .class selector selects all elements with the specific class. The class refers to the class attribute of an HTML element.

        </span>

    </div>
    <hr />

    <div class="rightChild code">
        <span STYLE="font-weight:bold">Get it visualized by selecting a class... </span><br>
        <!-- <p> <span> $(' <input type="text" id="find" name="find" placeholder="element name.."> ')</span> </p> -->

        <label for="element">Choose an element : </label>
        <span>
            $('#
            <select name="element" id="find">
                <option value="">Select</option>
                <option value="Heading">heading</option>
                <option value="Parahraph">Parahraph</option>
                <option value="ClassA">Class-A </option>
                <option value="ClassB">Class-B</option>
                <option value="name">name</option>
                <option value="email">email</option>

            </select> ')
        </span>


        <input style="margin-left: 1rem;" type="button" id="class-Button" value="Try out !!" />
        <input style="margin-left: 1rem;" type="button" id="class-reset" value="Reset.." />
        <div id="display"></div>
        <div id="myDiv" style="display: none;">hii</div>
        <div id="code"></div>
        <div id="code2"></div>
    </div><hr />
    <div class="rightChild html-block">

        <h1 class="Heading" style="text-align:center">I'm < h1> with class "heading"</h1>
        <h2 class="SubHeading" style="text-align:center">I'm Sub heading with class "SubHeading"</h2>

        <p id="Parahraph">
            I'm < p> tag !! The < p> tag defines a paragraph.
            Browsers automatically add a single blank line before and after each < p> element.
        </p>

        <div style="display:inline-flex; text-align:center" id="boxes" ; class="BoxContainer">

            <div class="classA" id="ClassA">
                <h2>Class A</h2>
                <span class="spanText">
                    The < div> tag defines a division or a section in an HTML document.Browsers always place a line break before and after element.
                </span>
            </div>

            <div class="classB" id="ClassB">
                <h2>Class B</h2>
                <span class="spanText">
                    The < div> tag is used as a container for HTML elements - which is then styled with
                    CSS or manipulated with JavaScript.
                </span>
            </div>

            <div class="classC" id="ClassC">
                <h2>Class C:</h2>
                <span class="spanText">
                    The < div> tag is easily styled by using the class or id attribute. Any sort of
                    content can be put inside the < div> tag!
                </span>
            </div>
        </div><br />

        <hr />
        <br />

        <div style="background-color:aliceblue;">


            <form class="formDeatils">
                <div style="padding:4rem; text-align:center;">
                    <br />
                    <label for="name">Name:</label>
                    <input type="text" id="name" name="name">
                    <label for="email">Email:</label>
                    <input type="email" id="email" name="email"><br><br />

                    <label for="option1">Option 1:</label>
                    <input type="checkbox" id="option1" name="option1" value="option1">

                    <label for="option2">Option 2:</label>
                    <input type="checkbox" id="option2" name="option2" value="option2"><br><br />

                    <label for="gender">Gender:</label><br>
                    <input type="radio" id="male" name="gender" value="male">
                    <label for="male">Male</label>

                    <input type="radio" id="female" name="gender" value="female">
                    <label for="female">Female</label><br /><br />

                    <input type="button" value="submit" />
                    <input type="reset" value="reset" />
                    <input type="hidden" value="cancel" /><br />
                    <p></p>
                </div>
            </form>

        </div>
        <br />
        <br />

    </div>


</div>


<script>

    $(function () {
        $('#class-Button').click(function () {

            var elementName = $('#find').val();
            $('.rightChild.html-block').find('*').css({
                'background-color': '',
                'border': '',
                'color': 'black'
            });

            $('.rightChild.html-block').find("#" + elementName).css({
                'background-color': '#3445b4'
            });

            $('.rightChild.html-block').find("#" + elementName).css({
                'color': 'white'
            });
            $('.rightChild.html-block').find("#" + elementName).find('*').css({
                'color': 'white'
            });


            var container = $('#flex-child-right');
            var scrollTo = $("#" + elementName)[0];

            $(container).animate({
                scrollTop: $("#" + elementName).offset().top
            }, 1000);
        });

        // reset
        $('#class-reset').click(function () {
            $('#find').val = '';
            $('.rightChild.html-block').find('*').css({
                'background-color': '',
                'border': ''
            });

            $('.rightChild.html-block').find('*').css({
                'color': 'black'
            });
        });


    });

</script>